sftp:
  port: 2222
  host-key-provider: '.product/key.pem'
  user-properties: 'user.properties'
  s3:
    end-point: 'rgw.ceph:7480'
    protocol: 'HTTP'
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sftp
    password: